# Generated by Django 4.2.26 on 2026-03-07 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0037_press_allow_journal_a11y_info_press_ally_info'),
        ('journal', '0068_issue_cached_display_title_a11y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='press_association',
            field=models.ForeignKey(blank=True, help_text='The press this journal belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journals_list', to='press.press'),
        ),
    ]
